config/routes.rb
Rails.application.routes.draw do
  get 'reservations/update'

  resources :courts do
    member do
      get 'before_show'
      get 'show_admin'
      get 'before_show_admin'
    end
    resources :reservations do
      member do
        patch 'update'
        patch 'cancel'
      end
    end
  end

  root 'static_pages#top'
 
  devise_for :users, controllers: {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    omniauth_callbacks: "omniauth_callbacks"
  }

  resources :users do
    collection do
      post :import
    end
  end
  
end

app/models/court.rb
class Court < ApplicationRecord
  has_many :reservations, dependent: :destroy
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :admin_user, only: [:new, :edit, :show_admin, :index]
  before_action :non_admin_user, only: :show
  before_action :set_court, only: [:edit, :update, :show, :show_admin, :destroy]
  before_action :set_one_month, only: [:show, :show_admin]

  def new
    @court = Court.new
  end

  def create
    @court = Court.new(court_params)
    if @court.save
      flash[:success] = '新規作成に成功しました'
      redirect_to courts_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @court.update_attributes(court_params)
      flash[:success] = "更新しました。"
      redirect_to courts_url
    else
      render :edit
    end
  end

  def before_show
    redirect_to court_path(id: params[:court_id])
  end

  def show
  end

  def before_show_admin
    redirect_to show_admin_court_path(id: params[:court_id])
  end 

  def show_admin
  end

  def index
    @courts = Court.all.order(id: "ASC")
  end

  def destroy
    @court.destroy
    flash[:success] = "#{@court.court_name}のデータを削除しました。"
    redirect_to courts_url
  end 

  private
  
  def court_params
    params.require(:court).permit(:court_name, :court_note)
  end 

  def set_court
    @court = Court.find(params[:id])
  end

end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/_form.html.erb
<%= form_with(model: @court, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @court %>
  
  <%= f.label :court_name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :court_name, class: "form-control" %>
  
  <%= f.label :court_note, class: "label-#{yield(:class_text)}" %>
  <%= f.text_area :court_note, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/courts/edit.html.erb
<% provide(:title, 'Edit') %>
<% provide(:class_text, 'court-edit') %>
<% provide(:button_text, '更新') %>
<h1>テニスコートの更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/courts/index.html.erb
<% provide(:title, 'All-court') %>
<% provide(:class_text, 'All-court') %>
<% provide(:button_text, '一覧') %>

<h1 class="All-court-title">すべてのテニスコート</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-courts">
    <thead>
      <tr>
        <th class="court-name"><%= Court.human_attribute_name :court_name %></th>
        <th><%= Court.human_attribute_name :court_note %></th>
        <th></th>
      </tr>
    </thead>
    
    <% @courts.each do |court| %>
      <tr>     
        <td><%= court.court_name %></td>
        <td><%= court.court_note %></td>
        <td class="court-btn">
          <%= link_to "編集", edit_court_path(court), class: "btn btn-success" %>
          <%= link_to "削除", court, method: :delete,
              data: { confirm: "削除してよろしいですか？" },
              class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>

  <h4><%= link_to "テニスコート追加", new_court_path, class: "btn btn-primary" %></h4>

</div>

app/views/courts/index_reservation.html.erb
<% provide(:title, 'court-reservation') %>
<% provide(:class_text, 'court-reservation') %>
<% provide(:button_text, '予約状況') %>

<h1>予約状況</h1>

<table class="table table-bordered table-condensed user-table"  id="table-reservations">
  <tr>
    <td>
      <%= link_to "←", court_path(date: @first_day.prev_month), class: "btn btn-primary" %>
      &emsp;<%= l(@first_day, format: :middle) %>　予約表&emsp;
      <%= link_to "→", court_path(date: @first_day.next_month), class: "btn btn-primary" %>
    </td>
  </tr>
</table>

app/views/courts/new.html.erb
<% provide(:title, 'court-new') %>
<% provide(:class_text, 'court-new') %>
<% provide(:button_text, '新規作成') %>

<h1>テニスコート追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/courts/show.html.erb
<% provide(:title, @court.court_name) %>
<div>
  <table class="table table-condensed"  id="table-header">
    <tr>
      <td id="reservation-title">
        <% unless @first_day == Date.current.beginning_of_month %>
          <%= link_to "←", court_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          &emsp;<%= l(@first_day, format: :middle) %>　予約表&emsp;
          <%= link_to "→", court_path(date: @first_day.next_month), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "←", court_path(date: @first_day.prev_month), class: "btn btn-primary disabled" %>
          &emsp;<%= l(@first_day, format: :middle) %>　予約表&emsp;
          <%= link_to "→", court_path(date: @first_day.next_month), class: "btn btn-primary" %> 
        <% end %>       
      </td>
      <td id="reservation-right"><%= @court.court_name %></td>
      <td>
        <%= form_with model: @courts, url: before_show_court_path, method: :get, local: true do |f| %>
          <%= f.collection_select :court_id, Court.all, :id, :court_name, { id: "court_id", class: "court_class" } %>
          <%= f.submit "選択" %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-condensed" id="table-reservations">
    <thead>
      <tr>
        <th colspan="2">予約日</th>
        <th colspan="2">9:00~11:00</th>
        <th colspan="2">11:00~13:00</th>
        <th colspan="2">13:00~15:00</th>
        <th colspan="2">15:00~17:00</th>
        <th colspan="2">17:00~19:00</th>
      </tr>
    </thead>
     <tbody>
       <% @reservations.each do |day| %>
         <% css_class = case day.reservation_date.wday
                       when 6 then 'text-primary'
                       when 0 then 'text-danger'
                       end %>
         <tr>
           <td id="reservation-center"><%= l(day.reservation_date, format: :short2) %></td>
           <td class="<%= css_class %>"  id="reservation-center"><%= $days_of_the_week[day.reservation_date.wday] %></td>
           <!-- 9:00〜11:00の時間帯の内容 -->
           <td>
            <% if ((Date.current + 14) > day.reservation_date) && (day.reservation_date > Date.current) %>
              <% if day.part1.nil? || day.part1 == 99999 %>
                <%= link_to "予約", court_reservation_path(@court, day, part1: current_user.id, part1_time: Time.current), method: :patch, class: "btn btn-primary" %>
              <% elsif day.part1 == current_user.id %>
                <%= link_to "キャンセル", cancel_court_reservation_path(@court, day, part1: "99999", part1_time: Time.current), method: :patch, class: "btn btn-danger" %>
              <% end %>
            <% end %>
           </td>
           <td id="reservation-center">
            <% if day.part1.present? && day.part1 != 99999 %>
              <%= "予約済" %>
            <% end %>
           </td>
           <!-- 11:00〜13:00の時間帯の内容 -->
           <td>
            <% if ((Date.current + 14) > day.reservation_date) && (day.reservation_date > Date.current) %>
              <% if day.part2.nil? || day.part2 == 99999 %>
                <%= link_to "予約", court_reservation_path(@court, day, part2: current_user.id, part2_time: Time.current), method: :patch, class: "btn btn-primary" %>
              <% elsif day.part2 == current_user.id %>
                <%= link_to "キャンセル", cancel_court_reservation_path(@court, day, part2: "99999", part2_time: Time.current), method: :patch, class: "btn btn-danger" %>
              <% end %>
            <% end %>
           </td>
           <td id="reservation-center">
            <% if day.part2.present? && day.part2 != 99999 %>
              <%= "予約済" %>
            <% end %>
           </td>
           <!-- 13:00〜15:00の時間帯の内容 -->
           <td>
            <% if ((Date.current + 14) > day.reservation_date) && (day.reservation_date > Date.current) %>
              <% if day.part3.nil? || day.part3 == 99999 %>
                <%= link_to "予約", court_reservation_path(@court, day, part3: current_user.id, part3_time: Time.current), method: :patch, class: "btn btn-primary" %>
              <% elsif day.part3 == current_user.id %>
                <%= link_to "キャンセル", cancel_court_reservation_path(@court, day, part3: "99999", part3_time: Time.current), method: :patch, class: "btn btn-danger" %>
              <% end %>
            <% end %>
           </td>
           <td id="reservation-center">
            <% if day.part3.present? && day.part3 != 99999 %>
              <%= "予約済" %>
            <% end %>
           </td>
           <!-- 15:00〜17:00の時間帯の内容 -->
           <td>
            <% if ((Date.current + 14) > day.reservation_date) && (day.reservation_date > Date.current) %>
              <% if day.part4.nil? || day.part4 == 99999 %>
                <%= link_to "予約", court_reservation_path(@court, day, part4: current_user.id, part4_time: Time.current), method: :patch, class: "btn btn-primary" %>
              <% elsif day.part4 == current_user.id %>
                <%= link_to "キャンセル", cancel_court_reservation_path(@court, day, part4: "99999", part4_time: Time.current), method: :patch, class: "btn btn-danger" %>
              <% end %>
            <% end %>
           </td>
           <td id="reservation-center">
            <% if day.part4.present? && day.part4 != 99999 %>
              <%= "予約済" %>
            <% end %>
           </td>
           <!-- 17:00〜19:00の時間帯の内容 -->
           <td>
            <% if ((Date.current + 14) > day.reservation_date) && (day.reservation_date > Date.current) %>
              <% if day.part5.nil? || day.part5 == 99999 %>
                <%= link_to "予約", court_reservation_path(@court, day, part5: current_user.id, part5_time: Time.current), method: :patch, class: "btn btn-primary" %>
              <% elsif day.part5 == current_user.id %>
                <%= link_to "キャンセル", cancel_court_reservation_path(@court, day, part5: "99999", part5_time: Time.current), method: :patch, class: "btn btn-danger" %>
              <% end %>
            <% end %>
           </td>
           <td id="reservation-center">
            <% if day.part5.present? && day.part5 != 99999 %>
              <%= "予約済" %>
            <% end %>
           </td>         
         </tr>
       <% end %>  
     </tbody>
  </div>
</div>

app/views/courts/show_admin.html.erb
<% provide(:title, @court.court_name) %>
<div>
  <table class="table table-condensed"  id="table-header">
    <tr>
      <td id="reservation-title">
        <% unless @first_day == Date.current.beginning_of_month %>
          <%= link_to "←", show_admin_court_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          &emsp;<%= l(@first_day, format: :middle) %>　予約表&emsp;
          <%= link_to "→", show_admin_court_path(date: @first_day.next_month), class: "btn btn-primary" %>
        <% else %>
          <%= link_to "←", show_admin_court_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          &emsp;<%= l(@first_day, format: :middle) %>　予約表&emsp;
          <%= link_to "→", show_admin_court_path(date: @first_day.next_month), class: "btn btn-primary" %> 
        <% end %>       
      </td>
      <td id="reservation-right"><%= @court.court_name %></td>
      <td>
        <%= form_with model: @courts, url: before_show_admin_court_path, method: :get, local: true do |f| %>
          <%= f.collection_select :court_id, Court.all, :id, :court_name,{ id: "court_id", class: "court_class" } %>
          <%= f.submit "選択" %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-condensed" id="table-reservations">
    <thead>
      <tr>
        <th colspan="2">予約日</th>
        <th colspan="2">9:00~11:00</th>
        <th colspan="2">11:00~13:00</th>
        <th colspan="2">13:00~15:00</th>
        <th colspan="2">15:00~17:00</th>
        <th colspan="2">17:00~19:00</th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |day| %>
        <% css_class = case day.reservation_date.wday
                       when 6 then 'text-primary'
                       when 0 then 'text-danger'
                       end %>
        <tr>
          <td id="reservation-center"><%= l(day.reservation_date, format: :short2) %></td>
          <td class="<%= css_class %>" id="reservation-center"><%= $days_of_the_week[day.reservation_date.wday] %></td>
          <!-- 9:00〜11:00の時間帯の内容 -->
          <td>
            <% if day.part1.present? && day.part1 != 99999 %>
              <%= User.find_by(id: day.part1).name %>
            <% end %>
          </td>
          <td>
            <% if day.part1_time.present? %>
              <%= l(day.part1_time, format: :short) %>
            <% end %>
          </td>
          <!-- 11:00〜13:00の時間帯の内容 -->
          <td>
            <% if day.part2.present? && day.part2 != 99999 %>
              <%= User.find_by(id: day.part2).name %>
            <% end %>
          </td>
          <td>
            <% if day.part2_time.present? %>
              <%= l(day.part2_time, format: :short) %>
            <% end %>
          </td>
           <!-- 13:00〜15:00の時間帯の内容 -->
          <td>
            <% if day.part3.present? && day.part3 != 99999 %>
              <%= User.find_by(id: day.part3).name %>
            <% end %>
          </td>
          <td>
            <% if day.part3_time.present? %>
              <%= l(day.part3_time, format: :short) %>
            <% end %>
          </td>
          <!-- 15:00〜17:00の時間帯の内容 -->
          <td>
            <% if day.part4.present? && day.part4 != 99999 %>
              <%= User.find_by(id: day.part4).name %>
            <% end %>
          </td>
          <td>
            <% if day.part4_time.present? %>
              <%= l(day.part4_time, format: :short) %>
            <% end %>
          </td>
          <!-- 17:00〜19:00の時間帯の内容 -->
          <td>
            <% if day.part5.present? && day.part5 != 99999 %>
              <%= User.find_by(id: day.part5).name %>
            <% end %>
          </td>
          <td>
            <% if day.part5_time.present? %>
              <%= l(day.part5_time, format: :short) %>
            <% end %>
          </td>         
         </tr>
       <% end %>  
     </tbody>
  </div>
</div>