config/routes.rb
Rails.application.routes.draw do
  get 'reservations/update'

  resources :courts do
    member do
      get 'before_show'
      get 'show_admin'
      get 'before_show_admin'
    end
    resources :reservations do
      member do
        patch 'update'
        patch 'cancel'
      end
    end
  end

  root 'static_pages#top'
 
  devise_for :users, controllers: {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords",
    omniauth_callbacks: "omniauth_callbacks"
  }

  resources :users do
    collection do
      post :import
    end
  end
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", id="header">
  <div class="container">
    <!-- ロゴ --> 
    <% if logged_in? && (current_user.phone_number == "00000000000") %>
      <%= link_to "セレブエンジニア テニスコート", edit_user_path(current_user), id: "logo" %>
      <% flash[:info] = "電話番号を00000000000から修正してください" %>
    <% else %>
      <%= link_to "セレブエンジニア テニスコート", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <!-- トップへ -->
          <% if current_user.phone_number == "00000000000" %>
            <li><%= link_to "トップへ", edit_user_path(current_user), id: "header-list" %></li>
            <% flash[:info] = "電話番号を00000000000から修正してください" %>
          <% else %>
            <li><%= link_to "トップへ", root_path, id: "header-list" %></li>
          <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdown-title" aria-expanded="true">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <% unless current_user.admin? %>
                  <!-- テニスコート予約 -->
                  <% if current_user.phone_number == "00000000000" %>
                    <li><%= link_to "テニスコート予約", edit_user_path(current_user) %></li>
                    <% flash[:info] = "電話番号を00000000000から修正してください" %>
                  <% else %>
                    <li><%= link_to "テニスコート予約", court_path(Court.first) %></li>
                  <% end %>
                  <!-- プロフィール編集 -->
                  <% unless current_user.provider == "line" %>
                    <li><%= link_to "プロフィール修正", edit_user_registration_path %></li>
                  <% else %>
                    <li><%= link_to "プロフィール修正", edit_user_path(current_user) %></li>
                  <% end %>
                <% else %>
                  <li><%= link_to "すべての利用者", users_path %></li>
                  <li><%= link_to "すべてのテニスコート", courts_path %></li>
                  <li><%= link_to "テニスコート予約状況", show_admin_court_path(Court.first) %></li> 
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> 
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to "トップへ", root_path, id: "header-list" %></li>         
          <li><%= link_to "ログイン", user_session_path, id: "header-list" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="home" class="big-bg">
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, msg| %>
          <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
        <% end %>
      <%= yield %>
      </div>
    </div>
  </body>
</html>